import {
  cpSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
  openSync,
  closeSync,
} from "node:fs";
import path from "node:path";
import { registerRuntime } from "./local.ts";
import { binary, doctor, run } from "./commands.ts";
import {
  digest,
  hashFiles,
  nativePackages,
  readJson,
  runtimeFor,
  selection,
  stateFile,
  writeJson,
  type NativePackage,
  type Runtime,
} from "./project.ts";

export async function analyze(root: string, packages = nativePackages(root)) {
  const dir = stateFile(root, "analysis");
  mkdirSync(dir, { recursive: true });
  await run(
    root,
    [
      binary(root, "expo"),
      "export:embed",
      "--platform",
      "macos",
      "--entry-file",
      readJson(path.join(root, "package.json")).main ?? "index.ts",
      "--bundle-output",
      path.join(dir, "app.js"),
      "--sourcemap-output",
      path.join(dir, "app.map"),
      "--dev",
      "false",
      "--minify",
      "false",
      "--max-workers",
      "2",
    ],
    { env: { CI: "1" }, capture: true },
  );
  const map = readJson(path.join(dir, "app.map"));
  const used = new Set<string>();
  for (const source of map.sources as string[]) {
    for (const pkg of packages) {
      // Metro's source map can contain absolute paths or project-relative node_modules paths.
      if (
        source.startsWith(pkg.root + "/") ||
        source.includes(`/node_modules/${pkg.name}/`) ||
        source.startsWith(`node_modules/${pkg.name}/`)
      )
        used.add(pkg.name);
    }
  }
  const config = readJson(path.join(root, "app.json"));
  const result = selection(
    packages,
    used,
    config.expo?.extra?.legend?.include ?? [],
  );
  writeJson(stateFile(root, "selection-report.json"), {
    included: result.included.map((p) => p.name),
    excluded: result.excluded.map((p) => p.name),
    reasons: result.reasons,
    sources: map.sources,
  });
  return result;
}

export async function build(
  root: string,
  mode: "go" | "dev" | "preview" | "release",
  force = false,
): Promise<{ app: string; runtime: Runtime }> {
  const lock = stateFile(root, "build.lock");
  mkdirSync(path.dirname(lock), { recursive: true });
  try {
    const fd = openSync(lock, "wx");
    writeFileSync(fd, String(process.pid));
    closeSync(fd);
  } catch (error: any) {
    if (error.code !== "EEXIST") throw error;
    const pid = Number(readFileSync(lock, "utf8"));
    if (!Number.isInteger(pid) || pid <= 0)
      throw new Error(
        `Invalid build lock: ${lock}. Check for an active build before removing it.`,
      );
    try {
      process.kill(pid, 0);
    } catch (signalError: any) {
      if (signalError.code === "ESRCH") {
        rmSync(lock);
        return build(root, mode, force);
      }
    }
    throw new Error(
      `Another build owns this project (PID ${pid}). Wait for it to finish.`,
    );
  }
  try {
    const result = await buildUnlocked(root, mode, force);
    if (mode === "go") {
      registerRuntime(result.app);
      console.log("Legend Go registered. Apps will discover it automatically.");
    }
    return result;
  } finally {
    rmSync(lock, { force: true });
  }
}

async function buildUnlocked(
  root: string,
  mode: "go" | "dev" | "preview" | "release",
  force: boolean,
): Promise<{ app: string; runtime: Runtime }> {
  await doctor(root);
  const all = nativePackages(root);
  const productionGraph = mode === "release" || mode === "preview";
  const chosen = productionGraph
    ? await analyze(root, all)
    : { included: all, excluded: [] as NativePackage[] };
  if (
    mode === "go" &&
    all.some((p) => p.name === "@legend-apps/native-greeting")
  )
    throw new Error(
      "Build Go from the clean SDK starter, not the custom-module fixture app.",
    );
  const runtime = runtimeFor(root, chosen.included, mode);
  const productionHash = productionGraph
    ? hashFiles(root, [".legend/analysis/app.js"])
    : undefined;
  if (productionHash)
    runtime.fingerprint = digest(runtime.fingerprint + productionHash);
  const resultFile = stateFile(root, `${mode}-build.json`);
  if (!force && existsSync(resultFile)) {
    const existing = readJson(resultFile);
    if (
      existing.runtime.fingerprint === runtime.fingerprint &&
      existsSync(existing.app)
    ) {
      console.log(`Reusing ${existing.app}`);
      return existing;
    }
  }
  writeJson(stateFile(root, "native-selection.json"), {
    excluded: chosen.excluded.map((p) => p.name),
    included: chosen.included.map((p) => ({ name: p.name, root: p.root })),
  });
  const rnConfig = path.join(root, "react-native.config.js");
  const marker = "// Generated by Legend; extend with configuration plugins.";
  if (
    existsSync(rnConfig) &&
    !readFileSync(rnConfig, "utf8").startsWith(marker)
  )
    throw new Error(
      "Existing react-native.config.js is not Legend-managed. Compose the native selection explicitly before building.",
    );
  writeFileSync(
    rnConfig,
    `${marker}\nconst selection = require('./.legend/native-selection.json');\nmodule.exports = { dependencies: Object.fromEntries([\n...selection.included.map(p => [p.name, { root: p.root }]),\n...selection.excluded.map(name => [name, { platforms: { ios: null, macos: null, android: null } }])\n]) };\n`,
  );
  const pkg = readJson(path.join(root, "package.json"));
  pkg.expo ??= {};
  pkg.expo.autolinking ??= {};
  pkg.expo.autolinking.exclude = chosen.excluded.map((p) => p.name);
  writeJson(path.join(root, "package.json"), pkg);
  const preparation = digest(
    JSON.stringify({
      config: readJson(path.join(root, "app.json")),
      packages: chosen.included.map((p) => [
        p.name,
        hashFiles(p.root, [
          "package.json",
          p.json.codegenConfig?.jsSrcsDir ?? "src",
          ...readdirSync(p.root).filter((name) => name.endsWith(".podspec")),
        ]),
      ]),
      plugin: hashFiles(root, [
        "node_modules/@legend-apps/desktop-host",
        "node_modules/@legend-apps/desktop-config",
      ]),
    }),
  );
  const preparedFile = stateFile(root, "native-preparation.json");
  const needsPreparation =
    force ||
    !existsSync(preparedFile) ||
    readJson(preparedFile).fingerprint !== preparation ||
    !existsSync(path.join(root, "macos/Pods/Manifest.lock"));
  if (needsPreparation) {
    await run(
      root,
      [
        binary(root, "expo-desktop"),
        "prebuild",
        "--platform",
        "macos",
        "--template",
        "expo-desktop-template-bare-minimum@54.81.1-beta.5",
        "--no-install",
        ...(force ? ["--clean"] : []),
      ],
      { env: { CI: "1" }, capture: true },
    );
    // beta.5 copies all-platform template dependencies even for macOS. Preserve this
    // platform's installed manifest instead of silently adding uninstalled Windows packages.
    writeJson(path.join(root, "package.json"), pkg);
    // ReactCodegen's source glob must not pick up bindings from a previously larger graph.
    rmSync(path.join(root, "macos/build/generated"), {
      recursive: true,
      force: true,
    });
    await run(root, ["pod", "install"], {
      cwd: path.join(root, "macos"),
      env: { RCT_NEW_ARCH_ENABLED: "1" },
      capture: true,
    });
    writeJson(preparedFile, { fingerprint: preparation });
  }
  const nativeRoot = path.join(root, "macos");
  const workspace = readdirSync(nativeRoot).find((name) =>
    name.endsWith(".xcworkspace"),
  );
  if (!workspace)
    throw new Error("Prebuild did not produce a macOS workspace.");
  const name = workspace.slice(0, -".xcworkspace".length);
  const configuration = mode === "release" ? "Release" : "Debug";
  const derived = stateFile(root, "DerivedData");
  console.log(`Building ${mode} runtime (${configuration}, arm64)…`);
  // Export once for analysis; native build performs the normal production bundle step.
  await run(
    root,
    [
      "xcodebuild",
      "-workspace",
      path.join(nativeRoot, workspace),
      "-scheme",
      `${name}-macOS`,
      "-configuration",
      configuration,
      "-destination",
      "platform=macOS,arch=arm64",
      "-derivedDataPath",
      derived,
      "ARCHS=arm64",
      "ONLY_ACTIVE_ARCH=YES",
      "CODE_SIGNING_ALLOWED=NO",
      "-jobs",
      "8",
      "build",
    ],
    {
      env: { RCT_NEW_ARCH_ENABLED: "1", ENTRY_FILE: pkg.main ?? "index.ts" },
      capture: true,
    },
  );
  const products = path.join(derived, "Build", "Products", configuration);
  const product = readdirSync(products).find((name) => name.endsWith(".app"));
  if (!product) throw new Error("Build completed without an app product.");
  const destination = stateFile(root, `products/${mode}/${product}`);
  rmSync(destination, { recursive: true, force: true });
  mkdirSync(path.dirname(destination), { recursive: true });
  cpSync(path.join(products, product), destination, { recursive: true, verbatimSymlinks: true });
  if (
    mode === "release" &&
    !existsSync(path.join(destination, "Contents/Resources/main.jsbundle"))
  )
    throw new Error("Standalone build is missing its JavaScript bundle.");
  const result = {
    app: destination,
    runtime: runtimeFor(root, chosen.included, mode),
  };
  if (productionHash)
    result.runtime.fingerprint = digest(
      result.runtime.fingerprint + productionHash,
    );
  // prebuild can update package/config fields; cache the actual post-generation inputs.
  writeJson(
    path.join(destination, "Contents/Resources/legend-runtime.json"),
    result.runtime,
  );
  // Local standalone outputs remain ad-hoc. `legend package` signs a separate
  // staging copy with Developer ID for distribution.
  await run(
    root,
    ["codesign", "--force", "--deep", "--sign", "-", destination],
    { capture: true },
  );
  writeJson(resultFile, result);
  console.log(`Built ${destination}`);
  return result;
}
